# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-10-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_department', '0002_auto_20201022_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
